name: Build Docker Image

on:
  push:
    branches: 
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (RV64)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/oslab:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/oslab:rv64
      - name: Build and push (RV32)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: BITS=32
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/oslab:rv32
